---
- hosts: all 
  become_user: root
  gather_facts: no
  tasks:
  - name: touch api.txt
    file: path=/tmp/api.txt state=touch  mode=0777
  
  - name: touch a.txt
    file: path=/tmp/a.txt state=touchs  mode=0777
